2025-08-23T15:45:07.690032Z ERROR axum::core::error: ❌ SQLx error: Database(PgDatabaseError { severity: Error, code: "23514", message: "new row for relation \"enterprise\" violates check constraint \"enterprise_slug_check\"", detail: Some("Failing row contains (c93246e0-ab8f-448e-b5b2-e1fa8c920d3a, rtỷt, FFF, 2025-08-23 15:45:07.713842+00)."), hint: None, position: None, where: None, schema: Some("public"), table: Some("enterprise"), column: None, data_type: None, constraint: Some("enterprise_slug_check"), file: Some("execMain.c"), line: Some(2146), routine: Some("ExecConstraints") })
2025-08-23T15:47:50.250942Z ERROR axum::core::error: ❌ SQLx error: Database(PgDatabaseError { severity: Error, code: "23514", message: "new row for relation \"company\" violates check constraint \"company_slug_check\"", detail: Some("Failing row contains (f97b8d67-d305-4657-b284-4089e656c691, 00000000-0000-0000-0000-000000000000, ad, SS, 2025-08-23 15:47:50.154123+00)."), hint: None, position: None, where: None, schema: Some("public"), table: Some("company"), column: None, data_type: None, constraint: Some("company_slug_check"), file: Some("execMain.c"), line: Some(2146), routine: Some("ExecConstraints") })
2025-08-23T15:47:53.070338Z ERROR axum::core::error: ❌ SQLx error: Database(PgDatabaseError { severity: Error, code: "23503", message: "insert or update on table \"company\" violates foreign key constraint \"company_enterprise_id_fkey\"", detail: Some("Key (enterprise_id)=(00000000-0000-0000-0000-000000000000) is not present in table \"enterprise\"."), hint: None, position: None, where: None, schema: Some("public"), table: Some("company"), column: None, data_type: None, constraint: Some("company_enterprise_id_fkey"), file: Some("ri_triggers.c"), line: Some(2921), routine: Some("ri_ReportViolation") })
2025-08-23T15:48:18.723075Z ERROR axum::core::error: ❌ SQLx error: Database(PgDatabaseError { severity: Error, code: "23503", message: "insert or update on table \"company\" violates foreign key constraint \"company_enterprise_id_fkey\"", detail: Some("Key (enterprise_id)=(00000000-0000-0000-0000-000000000000) is not present in table \"enterprise\"."), hint: None, position: None, where: None, schema: Some("public"), table: Some("company"), column: None, data_type: None, constraint: Some("company_enterprise_id_fkey"), file: Some("ri_triggers.c"), line: Some(2921), routine: Some("ri_ReportViolation") })
2025-08-23T15:49:45.012960Z ERROR axum::core::error: ❌ SQLx error: Database(PgDatabaseError { severity: Error, code: "23503", message: "insert or update on table \"tenant\" violates foreign key constraint \"fk_tenant_company_same_enterprise\"", detail: Some("Key (enterprise_id, company_id)=(2bf1904f-4c5f-4539-9207-7877ce1b23a8, 3fbbfdeb-1272-40ea-90ac-35e126215557) is not present in table \"company\"."), hint: None, position: None, where: None, schema: Some("public"), table: Some("tenant"), column: None, data_type: None, constraint: Some("fk_tenant_company_same_enterprise"), file: Some("ri_triggers.c"), line: Some(2921), routine: Some("ri_ReportViolation") })
